data_marts:
  outputs:
    dev:
      dataset: data_marts
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      priority: interactive
      project: astrafy-bitcoin-project
      threads: 4
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
  target: dev

staging:
  outputs:
    dev:
      dataset: staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      priority: interactive
      project: astrafy-bitcoin-project
      threads: 4
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
  target: dev

